export const VIBE_CODERS_PRODUCT = {
  id: "prod_034",
  name: "Vibe Coders",
  description:
    "A 6-month AI-assisted coding mentorship program for Nigerian youth — build real digital products using Next.js, Tailwind, Supabase, and AI tools. Project-based, psychology-informed, VillageCircle-rooted.",
  category: "education" as const,
  status: "BUILDING" as const,
  pillar: "conviction" as const,
  version: "1.1.1",
  slug: "vibecoders",
  domain: "villagecircle.ng" as const,
  routePath: "/vibecoders",
  app: "villagecircle-web",
  serviceModule: "EduCenterModule",
  icon: "⚡",
  database: "postgres" as const,
  revenueModel:
    "Free community + Cohort ₦35k-₦60k + Premium ₦10k/month + Revenue share + Sponsored Rivers",
  monthlyRevenue: 0,
  users: "0",
  techStack: [
    "Next.js 15",
    "TypeScript",
    "Tailwind CSS",
    "Supabase",
    "Paystack",
    "Resend",
  ],
  teamSize: 2,
  timeline: "Q2 2026 — First cohort launch",
  priority: 4,
  tags: [
    "education",
    "mentorship",
    "vibe-coding",
    "ai",
    "nigeria",
    "youth",
    "fullstack",
    "project-based",
    "villagecircle",
  ],
  graduationTarget: {
    domain: "educenter.com.ng" as const,
    pillar: "education" as const,
  },
  links: { website: "https://villagecircle.ng/vibe-coders" },
  features: [
    "Structured 6-month arc: 2 months learning + 4 months building real products",
    "Psychology-informed two-step application: quick interest form → deep assessment after shortlisting",
    "Live cohort with fixed quarterly start dates",
    "Segmentation by profile: youth (18-25), professional (26-35), rural youth (smartphone-first)",
    "AI-assisted coding stack: Cursor, Claude Code, v0, Next.js 15, Tailwind, Supabase",
    "Business + product thinking woven into every module",
    "Multiple payment paths: one-time ₦35k-₦60k, 3-month installment, ISA, scholarship slots",
    "Revenue share: 5-15% from co-built products that generate paying users",
    "Sponsored Rivers: corporate partners sponsor cohort seats or curriculum modules",
    "WhatsApp community link on enrollment confirmation",
    "Premium membership: ₦10k/month for advanced resources + 1-on-1 mentor sessions",
    "Student portfolio page on graduation",
    "Project showcase and cohort leaderboard",
    "Admin dashboard: manage applicants, cohorts, payments, and student progress",
  ],
  challenges: [
    "Student retention over 6 months",
    "Nigeria-specific tools access (some AI tools geo-restricted)",
  ],
  opportunities: [
    "40M+ Nigerian informal entrepreneurs needing digital skills",
    "First AI-first coding program in Nigeria with VillageCircle brand credibility",
  ],
  createdAt: "2026-04-20",
  updatedAt: "2026-04-20",
};
